version: '3.8'

services:
  web:
    image: fj_redmine:alpha
    container_name: fj_web
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      REDMINE_DB_PASSWORD: P@ssw0rd
  db:
    image: mysql:8.4.3
    container_name: fj_db
    restart: always
    volumes:
      - redmine_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: redmine
volumes:
  redmine_db:
